# Mini RAG Chatbot Configuration

# Database Configuration
database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  database: ${POSTGRES_DB:rag_chatbot}
  user: ${POSTGRES_USER:raguser}
  password: ${POSTGRES_PASSWORD:ragpassword}
  pool_size: 10
  max_overflow: 20

# Embedding Model Configuration
embedding:
  model_name: "intfloat/multilingual-e5-small"
  # Alternative: "BAAI/bge-m3", "BAAI/bge-small-en-v1.5"
  dimension: 384
  batch_size: 32
  device: "cpu"  # or "cuda" if GPU available
  cache_dir: "D:/mini-rag-chatbot/models/embeddings"

# LLM Configuration
llm:
  provider: "ollama"  # Options: "ollama", "openai", "local"
  model_name: "qwen2.5:3b-instruct"
  # Alternative models: "phi3:3.8b", "llama3.2:3b"
  ollama_host: "http://localhost:11434"
  temperature: 0.0
  max_tokens: 300
  timeout: 120

# RAG Configuration
rag:
  top_k: 5
  score_threshold: 80
  max_context_length: 2048
  min_similarity: 0.2  # Cosine similarity minimum
  max_similarity: 0.8  # Cosine similarity maximum
  
  # Score calibration formula:
  # score = ((similarity - min_similarity) / (max_similarity - min_similarity)) * 100
  # Clamped to [0, 100]

# Data Preparation
data:
  seed_file: "data/sample_seed.sql"
  corpus_output: "data/corpus.jsonl"
  segments_output: "data/corpus_segments.jsonl"
  max_segment_length: 1000  # characters
  overlap: 100  # character overlap between segments

# Fine-tuning Configuration (LoRA)
finetuning:
  enabled: false
  base_model: "Qwen/Qwen2.5-1.5B-Instruct"
  output_dir: "out/lora-qwen25"
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  learning_rate: 0.0001
  num_epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 4
  warmup_steps: 100
  logging_steps: 10
  save_steps: 100

# Post-training Configuration
posttrain:
  fuse_adapter: true
  convert_to_gguf: true
  ollama_model_name: "qwen25-lora-rag"
  temp_dir: "/tmp/lora_deploy"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  workers: 1
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  rotation: "500 MB"
  retention: "10 days"
  log_file: "D:/mini-rag-chatbot/logs/app.log"

# Paths (all on D:\ drive)
paths:
  data_dir: "D:/mini-rag-chatbot/data"
  models_dir: "D:/mini-rag-chatbot/models"
  logs_dir: "D:/mini-rag-chatbot/logs"
  output_dir: "D:/mini-rag-chatbot/out"

